# Generated by Django 6.0.1 on 2026-01-13 04:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default=core.models.generate_account_number, max_length=10, unique=True),
        ),
    ]
