# Generated by Django 6.0.1 on 2026-01-13 04:04

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(default=core.models.generate_card_number, max_length=16, unique=True)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('expiry_date', models.CharField(default=core.models.generate_expiry_date, max_length=5)),
                ('cvv', models.CharField(default=core.models.generate_cvv, max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Fee Not Paid)'), ('ACTIVE', 'Active (Issued)'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('card_fee_paid', models.BooleanField(default=False)),
                ('card_fee_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debit_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
