# Generated by Django 6.0.1 on 2026-01-13 04:40

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cardapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(default=core.models.generate_pin, help_text='4-digit PIN for transaction authentication', max_length=4),
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('READY', 'Ready for Download'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('format_type', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('statement_file', models.FileField(blank=True, null=True, upload_to='statements/')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_count', models.IntegerField(default=0)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_type', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GAS', 'Gas'), ('INTERNET', 'Internet'), ('MOBILE', 'Mobile Phone'), ('INSURANCE', 'Insurance'), ('LOAN', 'Loan EMI'), ('CREDIT_CARD', 'Credit Card Bill'), ('OTHER', 'Other')], max_length=20)),
                ('provider_name', models.CharField(help_text='Name of the bill provider', max_length=100)),
                ('account_number', models.CharField(help_text='Your account number with the provider', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill Payment',
                'verbose_name_plural': 'Bill Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('HOME', 'Home Loan'), ('AUTO', 'Auto Loan'), ('EDUCATION', 'Education Loan'), ('BUSINESS', 'Business Loan')], max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate (%)', max_digits=5)),
                ('loan_term_months', models.IntegerField(help_text='Loan duration in months')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('purpose', models.TextField(help_text='Purpose of the loan')),
                ('employment_status', models.CharField(blank=True, help_text='Employment status of applicant', max_length=50)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('collateral_details', models.TextField(blank=True, help_text='Details of collateral if any')),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, help_text='Calculated monthly payment', max_digits=12)),
                ('total_repayment', models.DecimalField(decimal_places=2, default=0, help_text='Total amount to be repaid', max_digits=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-created_at'],
            },
        ),
    ]
