# Generated by Django 6.0.1 on 2026-01-13 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('transfer', 'Fund Transfer'), ('deposit', 'Deposit'), ('withdraw', 'Withdrawal'), ('bill_payment', 'Bill Payment'), ('loan_disbursal', 'Loan Disbursal'), ('loan_payment', 'Loan Payment')], max_length=20)),
                ('reference_number', models.CharField(help_text='Unique transaction reference', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(help_text='Transaction details')),
                ('from_account', models.CharField(blank=True, max_length=50)),
                ('to_account', models.CharField(blank=True, max_length=50)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Receipt',
                'verbose_name_plural': 'Transaction Receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
